; AMX Mod X plugins

; Admin Base - Always one has to be activated
admin.amxx ; admin base (required for any admin-related)
;adminsql.amxx ; admin base - SQL version (comment admin.amxx)

; Basic
admincmd.amxx ; basic admin console commands
adminhelp.amxx ; help command for admin console commands
adminslots.amxx ; slot reservation
multilingual.amxx ; multilingual management

; Menus
menufront.amxx ; front-end for admin menus
cmdmenu.amxx ; command menu (speech, settings)
plmenu.amxx ; players menu (kick, ban, client cmds.)
;telemenu.amxx ; teleport menu (Fun Module required!)
mapsmenu.amxx ; maps menu (vote, changelevel)
pluginmenu.amxx ; menus for commands/cvars organized by plugin

; Chat / Messages
adminchat.amxx ; console chat commands
antiflood.amxx ; prevent clients from chat-flooding the server
scrollmsg.amxx ; displays a scrolling message
imessage.amxx ; displays information messages
adminvote.amxx ; vote commands

; Map related
nextmap.amxx ; displays next map in mapcycle
mapchooser.amxx ; allows to vote for next map
timeleft.amxx ; displays time left on map

; Configuration
pausecfg.amxx ; allows to pause and unpause some plugins
statscfg.amxx ; allows to manage stats plugins via menu and commands

; Day of Defeat
stats.amxx ; stats on death or round end (DoD Module required!)
statssounds.amxx ; precache plugin for stats plugins
statslogging.amxx ; weapons stats logging (DoD Module required!)

; Custom - Add 3rd party plugins here
jl_awayfromkeyboardkicker.amxx ; monitors player activity to identify and manage players who are Away From Keyboard (AFK) for an extended period, ensuring active participation and fairness in gameplay
jl_deatheffectenhancer.amxx ; significantly enriches the visual and gameplay experience upon a player's death in-game
jl_instantspawner.amxx ; completely removes the spawn delay when players die
jl_machinegundeploymentenhancer.amxx ; enhances the deployment mechanism for machine guns in-game
jl_parachuteprovider.amxx ; provides a parachute to players when they are falling from a height, allowing for a slow and safe descent
jl_serverpauselogger.amxx ; improves server administration by logging and printing detailed information whenever the server is paused or unpaused using the "amx_pause_and_log" command or the built-in "pause" command (including via RCON or server console)
jl_playerhealer.amxx ; enables players to gradually recover health points over time
jl_scoreboardhotnameslider.amxx ; updates the server's hostname on the scoreboard to create a sliding text effect
jl_svcbadpreventer.amxx ; aims to prevent the SVC_BAD error from causing players to be kicked out of the server
jl_weaponsregistrationenhancer.amxx ; optimizes hit detection for various weapons in the game, ensuring more reliable and consistent registration of hits

;jl_nextmapselectionrandomizer.amxx ; automates the process of map selection, randomizing the next map from those listed in mapcycle.txt, ensuring a varied and unpredictable map rotation
;jl_staminaunlimiter.amxx ; eliminates stamina limitations for players
